"use client";

import { useEffect, useState } from "react";
import { deleteRow, listRows, saveRow } from "@/lib/data/store";
import type { Exhibitor, Participant, Ticket } from "@/lib/data/types";

export type SprintTwoView="fair"|"register"|"tickets";
const blankExhibitor:Exhibitor={id:"new",product_name:"",category:"AI SaaS",description:"",exhibitor_contact:""};
const blankTicket:Ticket={id:"new",category_name:"",price_amount:null,currency:"USD",inclusions:"",refund_policy:"Placeholder — final terms to be confirmed"};

export function SprintTwoViews({view,onNotice}:{view:SprintTwoView,onNotice:(n:string)=>void}){
  const[exhibitors,setExhibitors]=useState<Exhibitor[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[editing,setEditing]=useState<Exhibitor|Ticket|null>(null),[editType,setEditType]=useState<"fair"|"tickets">("fair"),[registered,setRegistered]=useState(false);
  const load=async()=>{try{const[e,t]=await Promise.all([listRows("digital_fair_exhibitors"),listRows("tickets")]);setExhibitors(e);setTickets(t)}catch(err){onNotice(err instanceof Error?err.message:"Could not load records")}};
  useEffect(()=>{load()},[]);
  const remove=async(type:"fair"|"tickets",id:string)=>{if(!confirm("Delete this record?"))return;try{await deleteRow(type==="fair"?"digital_fair_exhibitors":"tickets",id);await load();onNotice("Record deleted.")}catch(e){onNotice(e instanceof Error?e.message:"Delete failed")}};
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(editType==="fair"){await saveRow("digital_fair_exhibitors",{...(editing as Exhibitor),product_name:String(f.get("product_name")),category:String(f.get("category")),description:String(f.get("description")),exhibitor_contact:String(f.get("exhibitor_contact"))})}else{await saveRow("tickets",{...(editing as Ticket),category_name:String(f.get("category_name")),price_amount:f.get("price_amount")?Number(f.get("price_amount")):null,currency:String(f.get("currency")),inclusions:String(f.get("inclusions")),refund_policy:String(f.get("refund_policy"))})}setEditing(null);await load();onNotice("Saved — your change will persist after refresh.")}catch(err){onNotice(err instanceof Error?err.message:"Save failed")}};
  const register=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const row:Participant={id:"new",full_name:String(f.get("full_name")),email:String(f.get("email")),phone:String(f.get("phone")),academy_affiliation:String(f.get("academy_affiliation")),ticket_category:String(f.get("ticket_category")),registration_source:"goai_app",status:"registered"};await saveRow("participants",row);e.currentTarget.reset();setRegistered(true);onNotice("Registration saved. Welcome to GOAI Summit Malaysia 2026!")}catch(err){onNotice(err instanceof Error?err.message:"Registration failed — please retry")}};
  if(view==="fair")return <><Hero eyebrow="AI Digital Fair" title="Source what’s next." text="Discover AI SaaS, digital products and services—then start a conversation with the people building them." action={<button className="button" onClick={()=>{setEditType("fair");setEditing({...blankExhibitor})}}>＋ Add exhibitor</button>}/>{exhibitors.length===0?<div className="empty"><h2>No exhibitors yet — add one</h2></div>:<div className="card-grid">{exhibitors.map(x=><article className="card fair-card" key={x.id}><div className="product-icon">✦</div><span className="tag">{x.category}</span><h3>{x.product_name}</h3><p>{x.description}</p><a className="contact-link" href={`mailto:${x.exhibitor_contact}`}>{x.exhibitor_contact}</a><div className="card-actions"><button className="button ghost small" onClick={()=>{setEditType("fair");setEditing(x)}}>Edit</button><button className="button danger small" onClick={()=>remove("fair",x.id)}>Delete</button></div></article>)}</div>}{editing&&editType==="fair"&&<Modal title={editing.id==="new"?"Add exhibitor":"Edit exhibitor"} close={()=>setEditing(null)} submit={save}><Field name="product_name" label="Product name" value={(editing as Exhibitor).product_name} full required/><Select name="category" label="Category" value={(editing as Exhibitor).category} options={["AI SaaS","Digital product","Service"]}/><Field name="exhibitor_contact" label="Contact" value={(editing as Exhibitor).exhibitor_contact}/><Field name="description" label="Description" value={(editing as Exhibitor).description} full textarea/></Modal>}</>;
  if(view==="tickets")return <><Hero eyebrow="Ticket categories" title="Choose your summit experience." text="Current prices and policies are planning placeholders until organiser confirmation." action={<button className="button" onClick={()=>{setEditType("tickets");setEditing({...blankTicket})}}>＋ Add category</button>}/><div className="card-grid">{tickets.map((t,i)=><article className={`card ticket-card ${i===1?"featured":""}`} key={t.id}>{i===1&&<span className="tag">Popular</span>}<h3>{t.category_name}</h3><div className="price">{t.price_amount==null?"TBC":`${t.currency} ${t.price_amount}`}</div><p>{t.inclusions}</p><small>{t.refund_policy}</small><div className="card-actions"><button className="button ghost small" onClick={()=>{setEditType("tickets");setEditing(t)}}>Edit</button><button className="button danger small" onClick={()=>remove("tickets",t.id)}>Delete</button></div></article>)}</div>{editing&&editType==="tickets"&&<Modal title={editing.id==="new"?"Add ticket":"Edit ticket"} close={()=>setEditing(null)} submit={save}><Field name="category_name" label="Category" value={(editing as Ticket).category_name} full required/><Field name="price_amount" label="Price" value={(editing as Ticket).price_amount??""} type="number"/><Field name="currency" label="Currency" value={(editing as Ticket).currency}/><Field name="inclusions" label="Inclusions" value={(editing as Ticket).inclusions} full textarea/><Field name="refund_policy" label="Refund policy" value={(editing as Ticket).refund_policy} full textarea/></Modal>}</>;
  return <><Hero eyebrow="Register your interest" title="Malaysia is calling." text="Join founders, consultants and AI practitioners for five days of practical learning, sourcing and meaningful connection."/><div className="register-grid"><form className="registration card" onSubmit={register}><h2>{registered?"You’re on the list":"Tell us about yourself"}</h2>{registered?<div className="success-mark">✓</div>:<div className="form-grid"><Field name="full_name" label="Full name" value="" full required/><Field name="email" label="Email" value="" type="email" required/><Field name="phone" label="Phone" value="" required/><Field name="academy_affiliation" label="Academy / organisation" value="" full/><Select name="ticket_category" label="Ticket interest" value="Standard" options={tickets.map(t=>t.category_name).length?tickets.map(t=>t.category_name):["Standard","VIP","Group (5+)"]}/><div className="field"><label>&nbsp;</label><button className="button" type="submit">Save registration →</button></div></div>}</form><div className="embed-card"><div><span className="tag">Official form</span><h2>Prefer the GoHighLevel form?</h2><p>The official registration-of-interest form is available here too.</p></div><iframe title="GOAI Summit registration form" src="https://api.leadconnectorhq.com/widget/form/shV6023EIloyBbQTfkxe" loading="lazy"/></div></div></>;
}

function Hero({eyebrow,title,text,action}:{eyebrow:string,title:string,text:string,action?:React.ReactNode}){return <div className="hero-row"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lede">{text}</p></div>{action}</div>}
function Modal({title,close,submit,children}:{title:string,close:()=>void,submit:(e:React.FormEvent<HTMLFormElement>)=>void,children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="modal" onSubmit={submit}><h2>{title}</h2><div className="form-grid">{children}</div><div className="modal-actions"><button type="button" className="button ghost" onClick={close}>Cancel</button><button className="button">Save changes</button></div></form></div>}
function Field({name,label,value,type="text",full=false,required=false,textarea=false}:{name:string,label:string,value:string|number,type?:string,full?:boolean,required?:boolean,textarea?:boolean}){return <div className={`field ${full?"full":""}`}><label>{label}</label>{textarea?<textarea name={name} defaultValue={value}/>:<input name={name} type={type} defaultValue={value} required={required}/>}</div>}
function Select({name,label,value,options}:{name:string,label:string,value:string,options:string[]}){return <div className="field"><label>{label}</label><select name={name} defaultValue={value}>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
