"use client";

import { useEffect, useState } from "react";
import { deleteRow, listRows, saveRow } from "@/lib/data/store";
import type { Communication, Participant, Referral } from "@/lib/data/types";

export type SprintThreeView="crm"|"affiliates";
type Editing={kind:"communication";row:Communication}|{kind:"participant";row:Participant}|{kind:"referral";row:Referral};
const blankCommunication:Communication={id:"new",channel:"email",subject:"",audience_segment:"All registered",body_preview:"",status:"drafted",sent_at:null};
const blankReferral:Referral={id:"new",affiliate_name:"",referred_name:"",referred_email:"",sale_amount:null,currency:"USD",referral_status:"applied",payout_status:"pending",tax_note:""};

export function SprintThreeViews({view,onNotice}:{view:SprintThreeView,onNotice:(n:string)=>void}){
  const[communications,setCommunications]=useState<Communication[]>([]),[participants,setParticipants]=useState<Participant[]>([]),[referrals,setReferrals]=useState<Referral[]>([]),[tab,setTab]=useState<"participants"|"communications">("participants"),[editing,setEditing]=useState<Editing|null>(null);
  const load=async()=>{try{const[c,p,r]=await Promise.all([listRows("communications_log"),listRows("participants"),listRows("affiliate_referrals")]);setCommunications(c);setParticipants(p);setReferrals(r)}catch(e){onNotice(e instanceof Error?e.message:"Could not load CRM")}};
  useEffect(()=>{load()},[]);
  const remove=async(kind:Editing["kind"],id:string)=>{if(!confirm("Delete this record?"))return;try{await deleteRow(kind==="communication"?"communications_log":kind==="participant"?"participants":"affiliate_referrals",id);await load();onNotice("Record deleted.")}catch(e){onNotice(e instanceof Error?e.message:"Delete failed")}};
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);try{
    if(editing.kind==="communication")await saveRow("communications_log",{...editing.row,channel:String(f.get("channel")),subject:String(f.get("subject")),audience_segment:String(f.get("audience_segment")),body_preview:String(f.get("body_preview")),status:String(f.get("status")),sent_at:String(f.get("status"))==="sent"?(editing.row.sent_at??new Date().toISOString()):null});
    if(editing.kind==="participant")await saveRow("participants",{...editing.row,full_name:String(f.get("full_name")),email:String(f.get("email")),phone:String(f.get("phone")),academy_affiliation:String(f.get("academy_affiliation")),ticket_category:String(f.get("ticket_category")),status:String(f.get("status"))});
    if(editing.kind==="referral")await saveRow("affiliate_referrals",{...editing.row,affiliate_name:String(f.get("affiliate_name")),referred_name:String(f.get("referred_name")),referred_email:String(f.get("referred_email")),sale_amount:f.get("sale_amount")?Number(f.get("sale_amount")):null,currency:String(f.get("currency")),referral_status:String(f.get("referral_status")),payout_status:String(f.get("payout_status")),tax_note:String(f.get("tax_note"))});
    setEditing(null);await load();onNotice("Saved — your change will persist after refresh.");
  }catch(err){onNotice(err instanceof Error?err.message:"Save failed")}};
  if(view==="affiliates")return <><Hero eyebrow="Affiliate tracker" title="Turn introductions into growth." text="Track every referral from application through confirmation and payout." action={<button className="button" onClick={()=>setEditing({kind:"referral",row:{...blankReferral}})}>＋ Add referral</button>}/><Stats items={[["Referrals",referrals.length],["Confirmed",referrals.filter(r=>r.referral_status==="confirmed").length],["Sales value",`USD ${referrals.reduce((n,r)=>n+(r.sale_amount??0),0).toLocaleString()}`]]}/>{referrals.length===0?<div className="empty"><h2>No referrals yet</h2></div>:<div className="table-wrap"><table><thead><tr><th>Affiliate</th><th>Referred participant</th><th>Sale</th><th>Referral</th><th>Payout</th><th></th></tr></thead><tbody>{referrals.map(r=><tr key={r.id}><td><b>{r.affiliate_name}</b></td><td>{r.referred_name}<small>{r.referred_email}</small></td><td>{r.sale_amount==null?"—":`${r.currency} ${r.sale_amount}`}</td><td><span className={`status ${r.referral_status}`}>{r.referral_status}</span></td><td><span className={`status ${r.payout_status}`}>{r.payout_status}</span></td><td><div className="table-actions"><button onClick={()=>setEditing({kind:"referral",row:r})}>Edit</button><button onClick={()=>remove("referral",r.id)}>Delete</button></div></td></tr>)}</tbody></table></div>}{editing?.kind==="referral"&&<Editor editing={editing} close={()=>setEditing(null)} submit={submit}/>}</>;
  return <><Hero eyebrow="Organiser CRM" title="Keep every relationship moving." text="See registrations and record participant communications in one working view." action={<button className="button" onClick={()=>{setTab("communications");setEditing({kind:"communication",row:{...blankCommunication}})}}>＋ Log communication</button>}/><Stats items={[["Participants",participants.length],["Confirmed",participants.filter(p=>p.status==="confirmed").length],["Communications",communications.length]]}/><div className="filters"><button className={`pill ${tab==="participants"?"active":""}`} onClick={()=>setTab("participants")}>Participants</button><button className={`pill ${tab==="communications"?"active":""}`} onClick={()=>setTab("communications")}>Communications</button></div>{tab==="participants"?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Affiliation</th><th>Ticket</th><th>Status</th><th></th></tr></thead><tbody>{participants.length===0?<tr><td colSpan={6}>No participant registrations yet.</td></tr>:participants.map(p=><tr key={p.id}><td><b>{p.full_name}</b></td><td>{p.email}<small>{p.phone}</small></td><td>{p.academy_affiliation||"—"}</td><td>{p.ticket_category}</td><td><span className={`status ${p.status}`}>{p.status}</span></td><td><div className="table-actions"><button onClick={()=>setEditing({kind:"participant",row:p})}>Edit</button><button onClick={()=>remove("participant",p.id)}>Delete</button></div></td></tr>)}</tbody></table></div>:<div className="table-wrap"><table><thead><tr><th>Channel</th><th>Subject</th><th>Audience</th><th>Status</th><th>Timestamp</th><th></th></tr></thead><tbody>{communications.map(c=><tr key={c.id}><td><span className="tag">{c.channel}</span></td><td><b>{c.subject}</b><small>{c.body_preview}</small></td><td>{c.audience_segment}</td><td><span className={`status ${c.status}`}>{c.status}</span></td><td>{c.sent_at?new Date(c.sent_at).toLocaleDateString():"—"}</td><td><div className="table-actions"><button onClick={()=>setEditing({kind:"communication",row:c})}>Edit</button><button onClick={()=>remove("communication",c.id)}>Delete</button></div></td></tr>)}</tbody></table></div>}{editing&&<Editor editing={editing} close={()=>setEditing(null)} submit={submit}/>}</>;
}

function Editor({editing,close,submit}:{editing:Editing,close:()=>void,submit:(e:React.FormEvent<HTMLFormElement>)=>void}){let fields:React.ReactNode;if(editing.kind==="communication"){const r=editing.row;fields=<><Select name="channel" label="Channel" value={r.channel} options={["email","phone","sms"]}/><Select name="status" label="Status" value={r.status} options={["drafted","sent","failed"]}/><Field name="subject" label="Subject" value={r.subject} full required/><Field name="audience_segment" label="Audience" value={r.audience_segment} full/><Field name="body_preview" label="Notes / preview" value={r.body_preview} full textarea/></>}else if(editing.kind==="participant"){const r=editing.row;fields=<><Field name="full_name" label="Full name" value={r.full_name} full required/><Field name="email" label="Email" value={r.email} type="email" required/><Field name="phone" label="Phone" value={r.phone}/><Field name="academy_affiliation" label="Affiliation" value={r.academy_affiliation} full/><Field name="ticket_category" label="Ticket category" value={r.ticket_category}/><Select name="status" label="Status" value={r.status} options={["registered","confirmed","cancelled"]}/></>}else{const r=editing.row;fields=<><Field name="affiliate_name" label="Affiliate" value={r.affiliate_name} required/><Field name="referred_name" label="Referred name" value={r.referred_name} required/><Field name="referred_email" label="Referred email" value={r.referred_email} type="email" full/><Field name="sale_amount" label="Sale amount" value={r.sale_amount??""} type="number"/><Field name="currency" label="Currency" value={r.currency}/><Select name="referral_status" label="Referral status" value={r.referral_status} options={["applied","confirmed","pending"]}/><Select name="payout_status" label="Payout status" value={r.payout_status} options={["pending","approved","paid"]}/><Field name="tax_note" label="Tax note" value={r.tax_note} full/></>}return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="modal" onSubmit={submit}><h2>{editing.row.id==="new"?"Add":"Edit"} {editing.kind}</h2><div className="form-grid">{fields}</div><div className="modal-actions"><button type="button" className="button ghost" onClick={close}>Cancel</button><button className="button">Save changes</button></div></form></div>}
function Hero({eyebrow,title,text,action}:{eyebrow:string,title:string,text:string,action?:React.ReactNode}){return <div className="hero-row"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lede">{text}</p></div>{action}</div>}
function Stats({items}:{items:Array<[string,string|number]>}){return <div className="stats">{items.map(([k,v])=><div className="stat" key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>}
function Field({name,label,value,type="text",full=false,required=false,textarea=false}:{name:string,label:string,value:string|number,type?:string,full?:boolean,required?:boolean,textarea?:boolean}){return <div className={`field ${full?"full":""}`}><label>{label}</label>{textarea?<textarea name={name} defaultValue={value}/>:<input name={name} type={type} defaultValue={value} required={required}/>}</div>}
function Select({name,label,value,options}:{name:string,label:string,value:string,options:string[]}){return <div className="field"><label>{label}</label><select name={name} defaultValue={value}>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
