"use client";

import { useEffect, useState } from "react";
import { deleteRow, listRows, saveRow } from "@/lib/data/store";
import type { Exhibitor, Ticket } from "@/lib/data/types";

export type SprintTwoView="fair"|"register"|"tickets";
const blankExhibitor:Exhibitor={id:"new",product_name:"",category:"AI SaaS",description:"",exhibitor_contact:""};
const blankTicket:Ticket={id:"new",category_name:"",price_amount:null,currency:"USD",inclusions:"",refund_policy:"Placeholder — final terms to be confirmed"};

export function SprintTwoViews({view,onNotice,canEdit}:{view:SprintTwoView,onNotice:(n:string)=>void,canEdit:boolean}){
  const[exhibitors,setExhibitors]=useState<Exhibitor[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[editing,setEditing]=useState<Exhibitor|Ticket|null>(null),[editType,setEditType]=useState<"fair"|"tickets">("fair");
  const load=async()=>{try{const[e,t]=await Promise.all([listRows("digital_fair_exhibitors"),listRows("tickets")]);setExhibitors(e);setTickets(t)}catch(err){onNotice(err instanceof Error?err.message:"Could not load records")}};
  useEffect(()=>{load()},[]);
  const remove=async(type:"fair"|"tickets",id:string)=>{if(!confirm("Delete this record?"))return;try{await deleteRow(type==="fair"?"digital_fair_exhibitors":"tickets",id);await load();onNotice("Record deleted.")}catch(e){onNotice(e instanceof Error?e.message:"Delete failed")}};
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(editType==="fair"){await saveRow("digital_fair_exhibitors",{...(editing as Exhibitor),product_name:String(f.get("product_name")),category:String(f.get("category")),description:String(f.get("description")),exhibitor_contact:String(f.get("exhibitor_contact"))})}else{await saveRow("tickets",{...(editing as Ticket),category_name:String(f.get("category_name")),price_amount:f.get("price_amount")?Number(f.get("price_amount")):null,currency:String(f.get("currency")),inclusions:String(f.get("inclusions")),refund_policy:String(f.get("refund_policy"))})}setEditing(null);await load();onNotice("Saved — your change will persist after refresh.")}catch(err){onNotice(err instanceof Error?err.message:"Save failed")}};
  if(view==="fair")return <><Hero eyebrow="AI Digital Fair" title="Source what’s next." text="Discover AI SaaS, digital products and services—then start a conversation with the people building them." action={canEdit?<button className="button" onClick={()=>{setEditType("fair");setEditing({...blankExhibitor})}}>＋ Add exhibitor</button>:undefined}/>{exhibitors.length===0?<div className="empty"><h2>No exhibitors yet</h2></div>:<div className="card-grid">{exhibitors.map(x=><article className="card fair-card" key={x.id}><div className="product-icon">✦</div><span className="tag">{x.category}</span><h3>{x.product_name}</h3><p>{x.description}</p>{x.exhibitor_contact&&<a className="contact-link" href={`mailto:${x.exhibitor_contact}`}>{x.exhibitor_contact}</a>}{canEdit&&<div className="card-actions"><button className="button ghost small" onClick={()=>{setEditType("fair");setEditing(x)}}>Edit</button><button className="button danger small" onClick={()=>remove("fair",x.id)}>Delete</button></div>}</article>)}</div>}{canEdit&&editing&&editType==="fair"&&<Modal title={editing.id==="new"?"Add exhibitor":"Edit exhibitor"} close={()=>setEditing(null)} submit={save}><Field name="product_name" label="Product name" value={(editing as Exhibitor).product_name} full required/><Select name="category" label="Category" value={(editing as Exhibitor).category} options={["AI SaaS","Digital product","Service","Digital Fair Partner"]}/><Field name="exhibitor_contact" label="Contact" value={(editing as Exhibitor).exhibitor_contact}/><Field name="description" label="Description" value={(editing as Exhibitor).description} full textarea/></Modal>}</>;
  if(view==="tickets")return <><Hero eyebrow="Ticket packages" title="Choose your summit experience." text="Official GOAI Summit Malaysia 2026 package pricing." action={canEdit?<button className="button" onClick={()=>{setEditType("tickets");setEditing({...blankTicket})}}>＋ Add category</button>:undefined}/><div className="card-grid">{tickets.map((t,i)=><article className={`card ticket-card ${i===1?"featured":""}`} key={t.id}>{i===1&&<span className="tag">Popular</span>}<h3>{t.category_name}</h3><div className="price">{t.price_amount==null?"TBC":`${t.currency} ${new Intl.NumberFormat("en-US").format(t.price_amount)}`}</div>{["Executive Package","VIP Executive Package","Elite Presidential"].includes(t.category_name)?<p>Package details are available through official registration.</p>:<><p>{t.inclusions}</p><small>{t.refund_policy}</small></>}{canEdit&&<div className="card-actions"><button className="button ghost small" onClick={()=>{setEditType("tickets");setEditing(t)}}>Edit</button><button className="button danger small" onClick={()=>remove("tickets",t.id)}>Delete</button></div>}</article>)}</div>{canEdit&&editing&&editType==="tickets"&&<Modal title={editing.id==="new"?"Add ticket":"Edit ticket"} close={()=>setEditing(null)} submit={save}><Field name="category_name" label="Category" value={(editing as Ticket).category_name} full required/><Field name="price_amount" label="Price" value={(editing as Ticket).price_amount??""} type="number"/><Field name="currency" label="Currency" value={(editing as Ticket).currency}/><Field name="inclusions" label="Inclusions" value={(editing as Ticket).inclusions} full textarea/><Field name="refund_policy" label="Refund policy" value={(editing as Ticket).refund_policy} full textarea/></Modal>}</>;
  return <><Hero eyebrow="Official registration" title="Register for GOAI Summit Malaysia 2026." text="Complete the official registration form below to reserve your interest in the summit."/><div className="official-registration"><div className="embed-card"><div><span className="tag">Official form</span><h2>Summit registration</h2><p>This is the only official registration form for GOAI Summit Malaysia 2026.</p></div><iframe title="Official GOAI Summit Malaysia 2026 registration form" src="https://api.leadconnectorhq.com/widget/form/shV6023EIloyBbQTfkxe" loading="lazy"/></div></div></>;
}

function Hero({eyebrow,title,text,action}:{eyebrow:string,title:string,text:string,action?:React.ReactNode}){return <div className="hero-row"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lede">{text}</p></div>{action}</div>}
function Modal({title,close,submit,children}:{title:string,close:()=>void,submit:(e:React.FormEvent<HTMLFormElement>)=>void,children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="modal" onSubmit={submit}><h2>{title}</h2><div className="form-grid">{children}</div><div className="modal-actions"><button type="button" className="button ghost" onClick={close}>Cancel</button><button className="button">Save changes</button></div></form></div>}
function Field({name,label,value,type="text",full=false,required=false,textarea=false}:{name:string,label:string,value:string|number,type?:string,full?:boolean,required?:boolean,textarea?:boolean}){return <div className={`field ${full?"full":""}`}><label>{label}</label>{textarea?<textarea name={name} defaultValue={value}/>:<input name={name} type={type} defaultValue={value} required={required}/>}</div>}
function Select({name,label,value,options}:{name:string,label:string,value:string,options:string[]}){return <div className="field"><label>{label}</label><select name={name} defaultValue={value}>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
