"use client";

import { useEffect, useMemo, useState } from "react";
import { dataMode, deleteRow, listRows, saveRow } from "@/lib/data/store";
import type { Person, Session } from "@/lib/data/types";
import { SprintTwoViews, type SprintTwoView } from "./SprintTwoViews";
import { SprintThreeViews, type SprintThreeView } from "./SprintThreeViews";
import { useAuth } from "./AuthProvider";

type View="itinerary"|"people"|SprintTwoView|SprintThreeView;
const icons:Record<View,string>={itinerary:"◷",people:"◎",fair:"✦",register:"↗",tickets:"◇",crm:"▦",affiliates:"↗"};
const blankSession:Session={id:"new",day_number:1,day_date:"2026-12-16",day_label:"Day 1 — Wednesday, 16 Dec",start_time:"09:00",end_time:"10:00",title:"",session_type:"summit",location:"Genting Highlands",speakers:[],theme:"Summit Inauguration & Expert Onboarding",sort_order:1};
const blankPerson:Person={id:"new",name:"",category:"faculty",role_title:"",organisation:"",bio:""};

export function SummitApp({initialView="itinerary"}:{initialView?:View}){
  const{user,isAdmin,loading:authLoading,signOut}=useAuth();
  const[view,setView]=useState<View>(initialView),[menu,setMenu]=useState(false),[sessions,setSessions]=useState<Session[]>([]),[people,setPeople]=useState<Person[]>([]);
  const[day,setDay]=useState(0),[category,setCategory]=useState("all"),[editing,setEditing]=useState<Session|Person|null>(null),[kind,setKind]=useState<"itinerary"|"people">("itinerary"),[notice,setNotice]=useState("");
  const load=async()=>{try{const[s,p]=await Promise.all([listRows("schedule_sessions"),listRows("people")]);setSessions(s);setPeople(p)}catch(e){setNotice(e instanceof Error?e.message:"Could not load data")}};
  useEffect(()=>{load()},[]);
  const navigate=(v:View)=>{setView(v);setMenu(false);history.replaceState(null,"",v==="itinerary"?"/":`/${v}`)};
  const remove=async(type:"itinerary"|"people",id:string)=>{if(!confirm("Delete this record? This cannot be undone."))return;try{await deleteRow(type==="itinerary"?"schedule_sessions":"people",id);await load();setNotice("Record deleted.")}catch(e){setNotice(e instanceof Error?e.message:"Delete failed")}};
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);try{
    if(kind==="itinerary"){const old=editing as Session,n=Number(form.get("day_number"));const labels=["","Day 1 — Wednesday, 16 Dec","Day 2 — Thursday, 17 Dec","Day 3 — Friday, 18 Dec","Day 4 — Saturday, 19 Dec","Day 5 — Sunday, 20 Dec"];await saveRow("schedule_sessions",{...old,day_number:n,day_label:labels[n],day_date:["","2026-12-16","2026-12-17","2026-12-18","2026-12-19","2026-12-20"][n],title:String(form.get("title")),start_time:String(form.get("start_time")),end_time:String(form.get("end_time")),session_type:String(form.get("session_type")),location:String(form.get("location")),theme:String(form.get("theme")),speakers:String(form.get("speakers")).split(",").map(x=>x.trim()).filter(Boolean),sort_order:Number(form.get("sort_order"))})}
    else{const old=editing as Person;await saveRow("people",{...old,name:String(form.get("name")),category:String(form.get("category")),role_title:String(form.get("role_title")),organisation:String(form.get("organisation")),bio:String(form.get("bio"))})}
    setEditing(null);await load();setNotice("Saved — your change will persist after refresh.")
  }catch(err){setNotice(err instanceof Error?err.message:"Save failed")}};
  const filteredPeople=useMemo(()=>category==="all"?people:people.filter(p=>p.category===category),[people,category]);
  const groups=useMemo(()=>[1,2,3,4,5].filter(n=>day===0||day===n).map(n=>({n,rows:sessions.filter(s=>s.day_number===n).sort((a,b)=>a.start_time.localeCompare(b.start_time)||(a.sort_order-b.sort_order))})),[sessions,day]);
  return <div className="app-shell">
    <aside className={`sidebar ${menu?"open":""}`}><div className="brand"><div className="brand-mark">GO</div><div><strong>GOAI Summit</strong><small>Malaysia 2026</small></div></div><nav className="nav">{(["itinerary","people","fair","register","tickets",...(isAdmin?["crm","affiliates"]:[])]as View[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>navigate(v)}><span>{icons[v]}</span>{v==="fair"?"Digital Fair":v==="crm"?"CRM":v[0].toUpperCase()+v.slice(1)}</button>)}</nav><div className="account-box">{authLoading?<span>Checking account…</span>:user?<><strong>{isAdmin?"Co-founder access":"Member account"}</strong><span>{user.email}</span><button onClick={signOut}>Sign out</button></>:<><strong>Join GOAI Summit</strong><span>Create an account, then register.</span><a href="/signup">Sign up / Sign in →</a></>}</div><div className="side-note"><strong>16–20 December 2026</strong>Genting Highlands & Kuala Lumpur</div></aside>
    <main className="main"><div className="promise"><button className="mobile-menu" onClick={()=>setMenu(!menu)}>☰</button><b>Learn. Source. Connect. Grow.</b><span>5 days · 4 nights · Malaysia</span></div><div className="content">
      {notice&&<div className={`notice ${/failed|could|error/i.test(notice)?"error":""}`}>{notice}<button style={{float:"right",border:0,background:"none"}} onClick={()=>setNotice("")}>×</button></div>}
      {dataMode==="local"&&<div className="notice">Demo storage is active on this device. Add the Supabase environment variables to switch persistence to the shared database.</div>}
      {(view==="crm"||view==="affiliates")&&!isAdmin?<AccessPanel loading={authLoading} signedIn={Boolean(user)}/>:view==="itinerary"?<><div className="hero-row"><div><div className="eyebrow">Your summit journey</div><h1>Five days designed for opportunity.</h1><p className="lede">Two focused summit days, an AI Digital Fair, landmark experiences and the conversations that move business forward.</p></div>{isAdmin&&<button className="button" onClick={()=>{setKind("itinerary");setEditing({...blankSession})}}>＋ Add session</button>}</div><div className="day-tabs"><button className={`pill ${day===0?"active":""}`} onClick={()=>setDay(0)}>All days</button>{[1,2,3,4,5].map(n=><button key={n} className={`pill ${day===n?"active":""}`} onClick={()=>setDay(n)}>Day {n}</button>)}</div>
        {sessions.length===0?<div className="empty"><h2>No sessions scheduled yet</h2>{isAdmin&&<button className="button" onClick={()=>{setKind("itinerary");setEditing({...blankSession})}}>Add the first session</button>}</div>:groups.map(g=><section className="timeline" key={g.n}><div className="day-head"><div><h2>{g.rows[0]?.day_label??`Day ${g.n}`}</h2><p>{g.rows[0]?.theme}</p></div><span className="tag">{g.rows.length} sessions</span></div>{g.rows.map(s=><article className="session" key={s.id}><div className="session-time">{s.start_time} — {s.end_time}</div><div><span className="tag">{s.session_type}</span><h3>{s.title}</h3><div className="meta">{s.location}{s.speakers?.length?` · ${s.speakers.join(" · ")}`:""}</div></div>{isAdmin&&<div className="card-actions"><button className="button ghost small" onClick={()=>{setKind("itinerary");setEditing(s)}}>Edit</button><button className="button danger small" onClick={()=>remove("itinerary",s.id)}>Delete</button></div>}</article>)}</section>)}
      </>:view==="people"?<><div className="hero-row"><div><div className="eyebrow">People of GOAI</div><h1>Meet the minds in the room.</h1><p className="lede">Faculty, partners, organisers and community members bringing practical experience from across the region.</p></div>{isAdmin&&<button className="button" onClick={()=>{setKind("people");setEditing({...blankPerson})}}>＋ Add person</button>}</div><div className="filters">{["all","faculty","partner","organiser","community"].map(c=><button key={c} className={`pill ${category===c?"active":""}`} onClick={()=>setCategory(c)}>{c[0].toUpperCase()+c.slice(1)}</button>)}</div>
        {filteredPeople.length===0?<div className="empty"><h2>No people listed yet</h2>{isAdmin&&<button className="button" onClick={()=>{setKind("people");setEditing({...blankPerson})}}>Add a person</button>}</div>:<div className="card-grid">{filteredPeople.map(p=><article className="card" key={p.id}><div className="avatar">{p.name.split(" ").slice(0,2).map(x=>x[0]).join("")}</div><h3>{p.name}</h3><span className="tag">{p.category}</span><p><b>{p.role_title}</b><br/>{p.organisation}</p><p>{p.bio}</p>{isAdmin&&<div className="card-actions"><button className="button ghost small" onClick={()=>{setKind("people");setEditing(p)}}>Edit</button><button className="button danger small" onClick={()=>remove("people",p.id)}>Delete</button></div>}</article>)}</div>}
      </>:view==="fair"||view==="register"||view==="tickets"?<SprintTwoViews view={view} onNotice={setNotice} canEdit={isAdmin}/>:<SprintThreeViews view={view} onNotice={setNotice}/>} {/* active view */}
    </div></main>
    {editing&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setEditing(null)}}><form className="modal" onSubmit={submit}><h2>{editing.id==="new"?"Add":"Edit"} {kind==="itinerary"?"session":"person"}</h2>{kind==="itinerary"?<SessionFields row={editing as Session}/>:<PersonFields row={editing as Person}/>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Cancel</button><button className="button">Save changes</button></div></form></div>}
  </div>
}

function AccessPanel({loading,signedIn}:{loading:boolean,signedIn:boolean}){return <div className="empty access-panel"><div className="lock-mark">◇</div><h2>{loading?"Checking access…":"Co-founder access only"}</h2>{!loading&&<><p>{signedIn?"Your member account can view the summit and submit registration, but cannot manage organiser data.":"Sign in with the summit co-founder account to manage CRM and affiliates."}</p>{!signedIn&&<a className="button" href="/signup">Sign in</a>}</>}</div>}

function SessionFields({row}:{row:Session}){return <div className="form-grid"><Field name="title" label="Session title" value={row.title} full required/><Field name="day_number" label="Day" value={row.day_number} type="number" required/><Field name="sort_order" label="Order" value={row.sort_order} type="number"/><Field name="start_time" label="Starts" value={row.start_time} type="time" required/><Field name="end_time" label="Ends" value={row.end_time} type="time"/><Select name="session_type" label="Type" value={row.session_type} options={["summit","fair","tour","break","meal","departure"]}/><Field name="location" label="Location" value={row.location}/><Field name="theme" label="Day theme" value={row.theme} full/><Field name="speakers" label="Speakers (comma separated)" value={row.speakers?.join(", ")} full/></div>}
function PersonFields({row}:{row:Person}){return <div className="form-grid"><Field name="name" label="Full name" value={row.name} full required/><Select name="category" label="Category" value={row.category} options={["faculty","partner","organiser","community"]}/><Field name="role_title" label="Role" value={row.role_title}/><Field name="organisation" label="Organisation" value={row.organisation} full/><Field name="bio" label="Profile" value={row.bio} full textarea/></div>}
function Field({name,label,value,type="text",full=false,required=false,textarea=false}:{name:string,label:string,value:string|number,type?:string,full?:boolean,required?:boolean,textarea?:boolean}){return <div className={`field ${full?"full":""}`}><label>{label}</label>{textarea?<textarea name={name} defaultValue={value}/>:<input name={name} type={type} defaultValue={value} required={required}/>}</div>}
function Select({name,label,value,options}:{name:string,label:string,value:string,options:string[]}){return <div className="field"><label>{label}</label><select name={name} defaultValue={value}>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
